backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "asia"
    label: "Asia Countries"

    folder: "content/asia"
    create: true
    delete: true

    slug: "{{slug}}"

    path: "{{slug}}/index"

    media_folder: ""
    public_folder: ""

    fields:
      - {
          label: "Country Name",
          name: "title",
          widget: "string"
        }